spring:
   datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
   h2:
      console:
         settings:
            trace: true 
         enabled: true
   jackson:
     date-format: dd/MM/yyyy
     time-zone: America/Sao_Paulo            
            
logging:
    level:
       root: info